spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/techelly/config-properties
                        username: techelly
                        password: password
